---
title: "Publications"
---

<!-- ## Publications and working papers> -->

<b> <a href="https://journals.sagepub.com/doi/full/10.1177/00223433241265028" target="_blank">When conflict becomes calamity: Understanding the role of armed conflict dynamics in natural disasters. <i> Journal of Peace Research </i> 2024.</a><br> </b>

<b> <a href="https://doi.org/10.1177/0022343320974096" target="_blank">Climate and cohesion: The effects of droughts on intra-ethnic and inter-ethnic trust, <i> Journal of Peace Research</i> 2021 (With Alexander De Juan). </a><br> </b>


<b> <a href="https://doi.org/10.1186/s40066-024-00512-1" target="_blank">The effect of traditional agricultural practices on the food consumption of households facing extreme weather events in Tanzania, <i> Agriculture & Food Security </i> 2025 (With Tim Wegenast, Roos Haer and Marce Birulés).</a><br> </b>

<b> <a href="https://www.peio.me/wp-content/uploads/PEIO17/submission_86.pdf" target="_blank">Who needs it the most: Climate risks as catalysts for climate adaptation aid allocation? <i> Working Paper.</i> (With Viktoria Jansesberger). </a><br> </b>

<b> How Natural Disaster Shape Political Institutions: Evidence
from Earthquakes and Income Tax Introductions. <i> Working Paper.</i> </b>

<b> Localized disparities in climate finance: The sub-national allocation of mitigation and adaptation funds in least developed dountries? <i> Working Paper.</i> (With Gabriele Spilker and Viktoria Jansesberger). </b>

<b> Social Trust in a Changing Climate: The Dual Impact of Environmental and Political Stressors. <i> Working Paper.</i> (With William Favell).</b>

<b> Protecting Against Nature By Protecting Nature: Evidence from Europe on Natural Disasters and Conservation. <i> Working Paper.</i> (With Austin Beacham).</b>

<b> Women’s empowerment and climate adaptation: Do joint land titles promote food security of households facing extreme weather events in Tanzania? <i> Working Paper.</i> (With Tim Wegenast and Roos Haer).</b>

<!-- ---- -->

<!-- <b> <a href="https://journals.sagepub.com/doi/full/10.1177/00223433241265028" target="_blank">When conflict becomes calamity: Understanding the role of armed conflict dynamics in natural disasters. <i> Journal of Peace Research </i> 2024.</a><br> </b> -->

<!-- Abstract: Can armed conflict amplify the societal impacts and humanitarian consequences of natural hazards? Given that these hazards affect millions of people worldwide and that climate change is expected to increase the frequency and intensity of extreme weather events, it is paramount that we advance our understanding of what makes societies vulnerable to these hazards. Existing research has focused mainly on political violence as a consequence of natural hazard-related disasters but has neglected that conflict can also be an underlying factor that shapes the impact of these events. Consequently, we know little about whether and how exposure to violent armed conflict increases vulnerability to natural hazards. This study argues that the local dynamics of conflict can have a significant effect on vulnerability and empirically investigates how periods of high-intensity conflict can affect the humanitarian consequences of natural hazards in the context of tropical cyclones in the Philippines. By combining data on physical storm exposure with highly detailed subnational data on disaster fatalities and conflict events, the empirical analysis allows the identification of the independent effect of conflict on hazard impacts. Results show that local periods of high-intensity conflict significantly increase the humanitarian consequences of natural hazards. These results have important implications for research investigating the impacts of disasters on peace and conflict, as they show that the consequences of natural disasters depend fundamentally on pre-existing conflict dynamics. -->


<!-- <b> <a href="https://doi.org/10.1177/0022343320974096" target="_blank">Climate and cohesion: The effects of droughts on intra-ethnic and inter-ethnic trust, <i> Journal of Peace Research</i> 2021 (With Alexander De Juan). </a><br> </b> -->

<!-- Abstract: While a large body of research has highlighted the conflict-inducing effects of climate change, we still know very little about the mechanisms linking environmental conditions to violent conflict. This article investigates the plausibility of a prominent channel according to which scarcity of natural resources can foster violent conflict through deteriorating intergroup relations. In addition to assessing the direct effects of adverse environmental conditions on intra-ethnic and inter-ethnic trust, we suggest a conditional argument on the role of horizontal inequality of hazard exposure. Environmental hazards are ‘unequal’ if they systematically affect ethnic groups differently. While inequality may reinforce intra-ethnic ties and out-group suspicion, equal hazard exposure may create a sense of unity among diverse victims in their collective struggle to cope with harsh environmental conditions. We test these arguments in the context of the severe drought periods that affected most East African countries in the years 2004 and 2005. The empirical analysis combines gridded information on drought severity with geo-located survey data across six countries in the region (Afrobarometer survey 2005/2006). Our main analyses find that exposure to drought hazards correlates positively with self-reported trust within and across ethnic groups. The latter association, however, depends on the degree of intergroup equality of hazard exposure and wanes as inequality increases. Taken together, these findings indicate that if droughts increase the risk of violent conflict, they seem to do so through mechanisms other than intergroup polarization and despite their positive association with ethnic trust. This is most likely the case in contexts where there is pronounced horizontal inequality of drought hazards. -->



<!-- <b> <a href="https://doi.org/10.1186/s40066-024-00512-1" target="_blank">The effect of traditional agricultural practices on the food consumption of households facing extreme weather events in Tanzania, <i> Agriculture & Food Security </i> 2025 (With Tim Wegenast, Roos Haer and Marce Birulés).</a><br> </b> -->

<!-- Abstract: An estimated 140 million people in Africa face acute malnutrition. By impacting agricultural production, climate change is likely to further decrease food consumption, particularly in sub-Saharan African states. Against this backdrop, various actors have called for more attention to alternative farming and food systems based on traditional agricultural knowledge capable of ensuring access to sufficient, nutritious, and safe food. So far, however, we have limited systematic evidence on which traditional agricultural practices may promote the food resilience of households exposed to extreme climatic conditions. Focusing on the most prevalent traditional diversification practices in Tanzania, this study assesses the extent to which crop diversification, annual crop intercropping, crop-tree intercropping, crop-livestock integration, and the cultivation of traditional crops increase the food availability and dietary diversity of smallholders facing extreme weather events in Tanzania. -->


<!-- <b> <a href="https://www.peio.me/wp-content/uploads/PEIO17/submission_86.pdf" target="_blank">Who needs it the most: Climate risks as catalysts for climate adaptation aid allocation? <i> Working Paper</i> (With Viktoria Jansesberger). </a><br> </b> -->

<!-- Astract: Which components of climate risk drive the allocation of climate adaptation aid at the sub-national level? Despite commitments from developed nations to assist vulnerable populations adapt to climate change, little is known about how donors prioritize different dimensions of climate risk at the local level. Existing studies have primarily examined cross-national aid allocation, focusing on whether donor interests outweigh recipients’ vulnerability. However, they often fail to distinguish between hazard exposure, vulnerability, and hazard impacts and rarely analyze regional allocations. This study addresses these gaps by analyzing the provincial distribution of multilateral climate adaptation projects in the Philippines. Using a novel panel dataset combining geo-coded adaptation projects with proxies for hazard exposure, vulnerability, and hazard impacts, we identify which factors influence aid allocation. Our results show that neither hazard exposure nor vulnerability consistently predict adaptation aid. Instead, recent hazard impacts - measured by cyclone-related fatalities - are the primary driver of aid distribution. This suggests that decision-makers prioritize immediate signals of human suffering over long-term structural vulnerability. These findings raise critical concerns about whether adaptation aid effectively supports long-term climate resilience and justice, highlighting the need for more transparent and strategic allocation mechanisms. -->



:::

